/**
 * HTML mockups for the Redirección flow.
 *
 * Ported from the legacy notificaciones-hsbc app.js FLOW_DEFINITIONS.redireccion.
 * Each export is a static HTML string. Primary buttons carry
 * `data-action="next"` — the PresentationMode root listens for clicks on
 * that selector and advances the step. Buttons that just illustrate state
 * (disabled OTP "Continuar", "regresa" links, etc.) deliberately omit it.
 *
 * Steps 2 and 10 are email captures and remain as static images
 * (mockupImageUrl). The rest are interactive HTML.
 *
 * CSS lives in flow-mockups.css and is already scoped under .flow-mockup-wrap.
 */

// --- Shared HSBC HTML helpers (inlined from legacy HSBC_HELPERS) ---

const iosStatus = `<div class="hsbc-ios-status"><span class="hsbc-ios-status-time">9:41</span><span class="hsbc-ios-status-icons"><svg width="16" height="12" viewBox="0 0 16 12" fill="#000"><rect x="0" y="3" width="3" height="9" rx="0.5"/><rect x="4" y="2" width="3" height="10" rx="0.5"/><rect x="8" y="0" width="3" height="12" rx="0.5"/><rect x="12" y="1" width="3" height="11" rx="0.5"/></svg><svg width="15" height="11" viewBox="0 0 15 11" fill="#000"><path d="M7.5 3.5C9.1 3.5 10.5 4.1 11.5 5.1L13 3.6C11.5 2.1 9.6 1.2 7.5 1.2S3.5 2.1 2 3.6L3.5 5.1C4.5 4.1 5.9 3.5 7.5 3.5z"/><circle cx="7.5" cy="8.5" r="2"/></svg><svg width="25" height="12" viewBox="0 0 25 12" fill="none"><rect x="0.5" y="0.5" width="21" height="11" rx="2" stroke="#000" stroke-opacity="0.35"/><rect x="2" y="2" width="16" height="8" rx="1" fill="#000"/><path d="M23 4v4a2 2 0 000-4z" fill="#000" opacity="0.4"/></svg></span></div>`;

const browserBar = (url: string) =>
  `<div class="hsbc-browser-bar"><div class="hsbc-address-bar"><svg class="hsbc-lock-icon" width="12" height="12" viewBox="0 0 24 24" fill="#adadad"><path d="M18 8h-1V6c0-2.76-2.24-5-5-5S7 3.24 7 6v2H6c-1.1 0-2 .9-2 2v10c0 1.1.9 2 2 2h12c1.1 0 2-.9 2-2V10c0-1.1-.9-2-2-2zM12 17c-1.1 0-2-.9-2-2s.9-2 2-2 2 .9 2 2-.9 2-2 2zm3.1-9H8.9V6c0-1.71 1.39-3.1 3.1-3.1s3.1 1.39 3.1 3.1v2z"/></svg><span>${url}</span></div></div>`;

const logo = `<div class="hsbc-logo-bar"><img src="/flows/redireccion/logo-hsbc.svg" alt="HSBC" class="hsbc-logo-img" style="height:28px;width:auto;"></div>`;

const footer = `<div class="hsbc-footer"><div class="hsbc-footer-label">Conéctate a nuestras redes sociales</div><div class="hsbc-social-icons"><div class="hsbc-social-circle"><svg width="16" height="16" viewBox="0 0 24 24" fill="#fff"><path d="M18 2h-3a5 5 0 00-5 5v3H7v4h3v8h4v-8h3l1-4h-4V7a1 1 0 011-1h3z"/></svg></div><div class="hsbc-social-circle"><svg width="14" height="14" viewBox="0 0 24 24" fill="#fff"><path d="M18.244 2.25h3.308l-7.227 8.26 8.502 11.24H16.17l-5.214-6.817L4.99 21.75H1.68l7.73-8.835L1.254 2.25H8.08l4.713 6.231zm-1.161 17.52h1.833L7.084 4.126H5.117z"/></svg></div><div class="hsbc-social-circle"><svg width="16" height="16" viewBox="0 0 24 24" fill="#fff"><polygon points="23,7 16,12 23,17"/><rect x="1" y="5" width="15" height="14" rx="2"/></svg></div></div></div>`;

const pinIcon = (size = 22) =>
  `<svg class="hsbc-pin-icon" width="${size}" height="${size}" viewBox="0 0 24 24" fill="#DB0011"><path d="M12 2C8.13 2 5 5.13 5 9c0 5.25 7 13 7 13s7-7.75 7-13c0-3.87-3.13-7-7-7zm0 9.5c-1.38 0-2.5-1.12-2.5-2.5s1.12-2.5 2.5-2.5 2.5 1.12 2.5 2.5-1.12 2.5-2.5 2.5z"/></svg>`;

const homeIndicator = `<div class="hsbc-home-indicator"></div>`;

// --- Step mockups ---

/** Step 1 — SMS de notificación. Click on the tracking link advances. */
export const step1Sms = `<div class="hsbc-screen hsbc-sms-screen">${iosStatus}<div class="hsbc-sms-top-bar"><span class="hsbc-sms-back">‹</span><div class="hsbc-sms-contact"><div class="hsbc-sms-avatar"><svg width="24" height="24" viewBox="0 0 24 24" fill="#fff"><path d="M12 12c2.21 0 4-1.79 4-4s-1.79-4-4-4-4 1.79-4 4 1.79 4 4 4zm0 2c-2.67 0-8 1.34-8 4v2h16v-2c0-2.66-5.33-4-8-4z"/></svg></div><div class="hsbc-sms-name">HSBC</div><div class="hsbc-sms-subtitle">Mensaje de texto</div></div><div style="width:28px"></div></div><div class="hsbc-sms-body"><div class="hsbc-sms-bubble">Tu solicitud de redirección se ha realizado con éxito, para más información entra aquí <span class="hsbc-sms-link" data-action="next" role="button">rastreo.kublau.121</span></div><div class="hsbc-sms-time">10:32 AM</div></div><div style="flex:1"></div>${homeIndicator}</div>`;

/** Step 3 — Advertencia de seguridad. "Continuar" advances. */
export const step3Advertencia = `<div class="hsbc-screen hsbc-overlay-screen">${iosStatus}${browserBar("hsbc.kublau.com")}<div class="hsbc-overlay-bg"><div class="hsbc-overlay-card"><div class="hsbc-warning-title">ADVERTENCIA</div><div class="hsbc-warning-text">Este sitio <strong>nunca</strong> te solicitará datos privados como:</div><ul class="hsbc-warning-list"><li>Número de tarjeta</li><li>Código de seguridad</li><li>Claves personales de acceso a banca móvil</li></ul><div class="hsbc-warning-small">El servicio de cambio de domicilio es operado por un tercero a solicitud de HSBC México.</div><button class="hsbc-btn-red" data-action="next" type="button">Continuar</button></div></div>${footer}</div>`;

/** Step 4 — Verificar dirección actual. CTA advances. */
export const step4Verificar = `<div class="hsbc-screen hsbc-web-screen">${iosStatus}${browserBar("hsbc.kublau.com")}${logo}<div class="hsbc-web-content"><div class="hsbc-web-title">Verifica tu dirección de entrega</div><div class="hsbc-address-card">${pinIcon(22)}<div class="hsbc-address-text"><strong>Calle Julio Verne 11 int. 7</strong><br>Polanco IV Secc. CP 11450, México.</div></div><div class="hsbc-yellow-box"><div class="hsbc-yellow-box-icon"><svg width="20" height="20" viewBox="0 0 24 24" fill="#333"><path d="M1 21h22L12 2 1 21zm12-3h-2v-2h2v2zm0-4h-2v-4h2v4z"/></svg></div><div class="hsbc-yellow-box-text">Recuerda que solo puedes redireccionar <strong>dentro del mismo estado</strong> o zona metropolitana (CDMX + Edo. Mex).<br><br>En caso de requerir el cambio a <strong>otro estado</strong>, deberás comunicarte al <span class="hsbc-link-blue">55 5721 1188 opc 2</span></div></div><button class="hsbc-btn-red" data-action="next" type="button" style="margin-bottom:16px;">Quiero cambiar mi dirección de entrega</button><div style="font-size:13px;color:#868686;text-align:center;">Si la dirección es correcta, puedes cerrar esta ventana</div></div>${footer}</div>`;

/** Step 5 — Verificación de seguridad (envío OTP). CTA advances. */
export const step5Verificacion = `<div class="hsbc-screen hsbc-web-screen">${iosStatus}${browserBar("hsbc.com.mx")}${logo}<div class="hsbc-web-content"><div class="hsbc-icon-centered"><svg width="33" height="33" viewBox="0 0 24 24" fill="#DB0011"><path d="M20 4H4c-1.1 0-1.99.9-1.99 2L2 18c0 1.1.9 2 2 2h16c1.1 0 2-.9 2-2V6c0-1.1-.9-2-2-2zm0 4l-8 5-8-5V6l8 5 8-5v2z"/></svg></div><div class="hsbc-security-title">Verificación de seguridad</div><div class="hsbc-security-desc">Te enviaremos un código de verificación al correo que tienes registrado con nosotros <strong>ra************</strong></div><div class="hsbc-gray-warning">En caso de que ya no tengas acceso a ese correo electrónico, comunícate al <span class="hsbc-link-blue">55 5721 3390</span> o acude a tu sucursal más cercana.</div><div class="hsbc-bullet-list"><div class="hsbc-bullet-title">Toma en cuenta lo siguiente:</div><ul><li>El Código puede demorar hasta 1 minuto</li><li>Verifica tu bandeja de spam</li><li>Solo podrás generar el código dos veces. Si necesitas uno nuevo, deberás comunicarte al <span class="hsbc-link-blue">55 5721 1188 opc 2</span></li></ul></div><button class="hsbc-btn-red" data-action="next" type="button" style="background:#df202f;">Enviar código</button></div>${footer}</div>`;

/** Step 6 — Ingresar código OTP. "Continuar" advances (even though visually disabled). */
export const step6Codigo = `<div class="hsbc-screen hsbc-web-screen">${iosStatus}${browserBar("hsbc.com.mx")}${logo}<div class="hsbc-web-content"><div class="hsbc-icon-centered"><svg width="33" height="33" viewBox="0 0 24 24" fill="#DB0011"><path d="M20 4H4c-1.1 0-1.99.9-1.99 2L2 18c0 1.1.9 2 2 2h16c1.1 0 2-.9 2-2V6c0-1.1-.9-2-2-2zm0 4l-8 5-8-5V6l8 5 8-5v2z"/></svg></div><div class="hsbc-code-title">Te enviaremos un código de seguridad a tu email <strong>ra***************</strong></div><div class="hsbc-code-helper">Si ya no cuentas con acceso a ese correo comunícate al <span class="hsbc-link-blue">55 5721 3390</span> para actualizar tus datos.</div><div class="hsbc-code-label">Escribe aquí tu código</div><div class="hsbc-code-sublabel">El código puede tardar hasta 1 minuto en llegar y expirará en 24 hrs</div><div class="hsbc-code-inputs"><div class="hsbc-code-box hsbc-code-box-empty"></div><div class="hsbc-code-box hsbc-code-box-empty"></div><div class="hsbc-code-box hsbc-code-box-empty"></div><div class="hsbc-code-box hsbc-code-box-empty"></div><div class="hsbc-code-box hsbc-code-box-empty"></div><div class="hsbc-code-box hsbc-code-box-empty"></div></div><div class="hsbc-code-resend">Si no lo recibiste puedes volver a solicitarlo</div><div class="hsbc-timer-badge-wrap"><div class="hsbc-timer-badge"><svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="#333" stroke-width="2"><circle cx="12" cy="12" r="10"/><polyline points="12 6 12 12 16 14"/></svg>00:51</div></div><button class="hsbc-btn-red" data-action="next" type="button">Continuar</button><div class="hsbc-code-warning">Si no recibiste tu código revisa tu bandeja de spam</div></div>${footer}</div>`;

/** Step 7 — Ingresar nueva dirección (form). "Guardar mi dirección" advances. */
export const step7Form = `<div class="hsbc-screen hsbc-web-screen">${iosStatus}${browserBar("hsbc.kublau.com")}${logo}<div class="hsbc-web-content"><div class="hsbc-web-title">Ingresa la dirección en la cual deseas recibir tu tarjeta</div><div class="hsbc-form-group"><div class="hsbc-form-label">Calle</div><input type="text" class="hsbc-form-input" placeholder="Ingresa tu calle"></div><div class="hsbc-form-row"><div class="hsbc-form-group"><div class="hsbc-form-label">Número ext.</div><input type="text" class="hsbc-form-input" placeholder="Ext."></div><div class="hsbc-form-group"><div class="hsbc-form-label">Número int.</div><input type="text" class="hsbc-form-input" placeholder="Int."></div></div><div class="hsbc-form-group"><div class="hsbc-form-label">Código postal</div><input type="text" class="hsbc-form-input" value="06100" placeholder="5 dígitos" maxlength="5"><div class="hsbc-form-valid"><svg width="14" height="14" viewBox="0 0 24 24" fill="#03781c"><path d="M9 16.17L4.83 12l-1.42 1.41L9 19 21 7l-1.41-1.41z"/></svg><span>Código postal válido</span></div></div><div class="hsbc-form-group"><div class="hsbc-form-label">Colonia</div><input type="text" class="hsbc-form-input" value="Hipódromo" placeholder="Colonia"></div><div class="hsbc-form-group"><div class="hsbc-form-label">Ciudad</div><input type="text" class="hsbc-form-input" value="Cuauhtémoc" placeholder="Ciudad"></div><div class="hsbc-form-group"><div class="hsbc-form-label">Estado</div><input type="text" class="hsbc-form-input" value="Ciudad de México" placeholder="Estado"></div><div class="hsbc-form-group"><div class="hsbc-form-label">Número de contacto</div><input type="tel" class="hsbc-form-input" placeholder="10 dígitos"></div><div class="hsbc-form-between-title">¿Entre qué calles está?</div><div class="hsbc-form-group"><div class="hsbc-form-label">Calle 1</div><input type="text" class="hsbc-form-input" placeholder="Calle 1"></div><div class="hsbc-form-group"><div class="hsbc-form-label">Calle 2</div><input type="text" class="hsbc-form-input" placeholder="Calle 2"></div><div class="hsbc-form-group"><div class="hsbc-form-label">Indicaciones y referencias</div><textarea class="hsbc-form-input hsbc-form-input-tall" placeholder="Ej: Edificio azul, junto a la farmacia..."></textarea></div><button class="hsbc-btn-red" data-action="next" type="button" style="margin-top:8px;margin-bottom:24px;">Guardar mi dirección</button></div>${footer}</div>`;

/** Step 8 — Confirmar dirección. "Confirmar" advances. */
export const step8Confirmar = `<div class="hsbc-screen hsbc-web-screen">${iosStatus}${browserBar("hsbc.kublau.com")}${logo}<div class="hsbc-web-content"><div class="hsbc-web-title">Tu tarjeta será enviada a la siguiente dirección:</div><div class="hsbc-address-card">${pinIcon(22)}<div class="hsbc-address-text"><strong>Calle Julio Verne 11 int. 7</strong><br>Polanco IV Secc. CP 11450, México.</div></div><button class="hsbc-btn-red" data-action="next" type="button" style="margin-bottom:16px;">Confirmar</button><div class="hsbc-confirm-text">Si la dirección no es correcta, <span class="hsbc-link-blue" data-action="prev" role="button">regresa</span> y modifica la información</div></div>${footer}</div>`;

/** Step 9 — Redirección exitosa. Terminal of the web flow; the screen itself can advance to the email step. */
export const step9Exito = `<div class="hsbc-screen hsbc-web-screen">${iosStatus}${browserBar("hsbc.kublau.com")}${logo}<div class="hsbc-web-content"><div class="hsbc-success-icon-wrap"><svg width="37" height="37" viewBox="0 0 40 40"><circle cx="20" cy="20" r="20" fill="#03781C"/><polyline points="12,20 18,26 28,14" fill="none" stroke="#fff" stroke-width="3" stroke-linecap="round" stroke-linejoin="round"/></svg></div><div class="hsbc-web-title">Tu solicitud de redirección se ha realizado con éxito</div><div class="hsbc-folio-card"><div class="hsbc-folio-label">Folio</div><div class="hsbc-folio-number">0103943523545345</div></div><div class="hsbc-success-text">También recibirás un mail con tu número de folio y la dirección a la que se enviará tu tarjeta</div><div class="hsbc-success-divider"></div><div class="hsbc-success-gray">Tu tarjeta será entregada en un lapso de <strong>5 a 10 días hábiles</strong>, cualquier duda comunícate al <span class="hsbc-link-blue">55 5721 1188 opc 2</span>.</div></div>${footer}</div>`;

/** Lookup by position. Used by migrations and seeds. */
export const REDIRECCION_MOCKUPS_HTML: Record<number, string> = {
  1: step1Sms,
  3: step3Advertencia,
  4: step4Verificar,
  5: step5Verificacion,
  6: step6Codigo,
  7: step7Form,
  8: step8Confirmar,
  9: step9Exito,
};
